In [14]:
import pandas as pd
import numpy as np  
import random

from sklearn.metrics.pairwise import cosine_similarity

In [15]:
matches = pd.read_csv('./data/whole_draft.csv', index_col=0)
matches

only_drafts = matches.drop(columns=['radiant_win', 'team'])

C:\Users\jrdor\AppData\Local\Temp\ipykernel_24588\2019325246.py:1: DtypeWarning: Columns (125) have mixed types. Specify dtype option on import or set low_memory=False.
  matches = pd.read_csv('./data/whole_draft.csv', index_col=0)

In [16]:
# def cosine_similarity(vec1, vec2):
#     vec1 = np.array(vec1)
#     vec2 = np.array(vec2)
#     dot_product = np.dot(vec1, vec2)
#     magnitude_vec1 = np.linalg.norm(vec1)
#     magnitude_vec2 = np.linalg.norm(vec2)
#     if magnitude_vec1 == 0 or magnitude_vec2 == 0:
#         return 0.0
#     similarity = dot_product / (magnitude_vec1 * magnitude_vec2)
#     return similarity

In [17]:
def generate_match_id(recent_match_id):
    return recent_match_id.index.max() + 1
match_id = generate_match_id(only_drafts)

def insert_match(match_db, match_id):
    new_row = pd.DataFrame([[0] * match_db.shape[1]], columns=match_db.columns, index=[match_id])
    
    return pd.concat([match_db, new_row])

insert_match(only_drafts, match_id)

,128,82,85,61,75,38,88,105,55,71,...,28,96,37,53,30,81,73,113,3,57
7276712204,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7276715296,0.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7276728072,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7276741510,0.0,2.0,0.0,0.0,2.0,0.0,0.0,1.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7276741939,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7881664207,0.0,0.0,1.0,2.0,0.0,0.0,2.0,2.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7881677439,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7881696382,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7881723710,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7881723711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
only_drafts.iloc[-1] = only_drafts.iloc[0]
last_row = only_drafts.iloc[-1].values

In [19]:
replacement_mapping = {1: 2, 2: 1}

reversed_last_row = [replacement_mapping.get(val, val) for val in last_row]

In [20]:
only_drafts.iloc[-1] = reversed_last_row

In [22]:
last_row = only_drafts.iloc[-1]

In [25]:
last_row = only_drafts.iloc[-1].to_numpy()
matrix = only_drafts.to_numpy()
dot_products = np.dot(matrix, last_row)
norms = np.linalg.norm(matrix, axis=1) * np.linalg.norm(last_row)
similarities = np.divide(dot_products, norms, out=np.zeros_like(dot_products), where=norms != 0)

In [30]:
similarity_scores = pd.Series(similarities[:-1], index=only_drafts.index[:-1])
similarity_scores

7276712204    0.800000
7276715296    0.100000
7276728072    0.350000
7276741510    0.416667
7276741939    0.250000
                ...
7881625418    0.166667
7881636100    0.116667
7881664207    0.383333
7881677439    0.250000
7881696382    0.183333
Length: 28405, dtype: float64

In [45]:
win_count = 0
is_team1 = True
for match_id in similarity_scores.index[:10]:
    radiant_win = matches.loc[match_id,'radiant_win']
    team_selected = matches.loc[match_id,'team']
    # if team_selected == 0 and radiant_win == True:
    #     print('A')
    # elif team_selected == 1 and radiant_win ==

A

In [40]:
matches

,128,82,85,61,75,38,88,105,55,71,...,37,53,30,81,73,113,3,57,radiant_win,team
7276712204,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,0.0
7276715296,0.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,0.0
7276728072,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True,0.0
7276741510,0.0,2.0,0.0,0.0,2.0,0.0,0.0,1.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,0.0
7276741939,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7881636100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,False,1.0
7881664207,0.0,0.0,1.0,2.0,0.0,0.0,2.0,2.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,True,1.0
7881677439,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,False,0.0
7881696382,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,0.0
7881723710,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True,0.0